name: diff-graph-env
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.11.12
  - graph-tool=2.97
  - pip
  - pip:
    - jupyter==1.1.1
    - notebook==7.4.2
    - pandas==2.2.3
    - numpy==2.2.6
    - scikit-learn==1.6.1
    - torch==2.7.0
    - torch-geometric==2.6.1
    - prettytable>=3.16,<3.17
    - kagglehub
    - plotly>=6.1,<6.2